osx_image: xcode7.1
language: objective-c
podfile: Example/Podfile

install:
- pip install --upgrade unittest2
- pip install --upgrade autobahntestsuite

script:
- wstest -m echoserver -w ws://localhost:9000
- xctool test
- pod lib lint