osx_image: xcode8.2
language: objective-c

podfile: Example/Podfile

install:
- if [[ ! $(which pip) ]]; then easy_install --user pip && export PATH=/Users/travis/Library/Python/2.7/bin:${PATH}; fi;
- pip install --user --upgrade unittest2
- pip install --user --upgrade autobahntestsuite
- if [[ ! $(which xcpretty) ]]; then gem install xcpretty --user-install; fi;

script:
- xcodebuild -workspace Example/RxWebSocket.xcworkspace -scheme RxWebSocket-Example -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.2' build | xcpretty
- wstest -m echoserver -w ws://127.0.0.1:9000 &
- xcodebuild -workspace Example/RxWebSocket.xcworkspace -scheme RxWebSocket-Example -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.2' test | xcpretty
- pod lib lint --no-clean --quick
