osx_image: xcode9
language: objective-c

install:
  - if [[ ! $(which pip) ]]; then easy_install --user pip && export PATH=/Users/travis/Library/Python/2.7/bin:${PATH}; fi;
  # - pip install -r requirements.txt
  - bundle install
#  - if [[ ! $(which xcpretty) ]]; then gem install xcpretty --user-install; fi;

script:
  # - wstest -m echoserver -w ws://127.0.0.1:9000 &
  - bundle exec fastlane ci
