osx_image: xcode7.2
language: objective-c

podfile: Example/Podfile

install:
- if [[ ! $(which pip) ]]; then easy_install --user pip && export PATH=/Users/travis/Library/Python/2.7/bin:${PATH}; fi;
- pip install --user --upgrade unittest2
- pip install --user --upgrade autobahntestsuite

script:
- xctool build
- wstest -m echoserver -w ws://127.0.0.1:9000 &
- xctool run-tests
- pod lib lint --no-clean --quick